# 应用名称
spring:
  application:
    name: computer
  # 应用服务 WEB 访问端口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: computer
    url: jdbc:mysql://localhost:3306/computer?serverTimezone=GMT
    username: root
    password: aaaaaa
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081

